import type { Metadata } from "next";
import { Noto_Serif_HK } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const notoSerifHK = Noto_Serif_HK({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSerifHK.className}  antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
